app/home/urls.py
# coding: utf-8

from django.conf.urls.defaults import *
from home.views import index,about,contact,coding,sitemap,robots,index_foolday

urlpatterns = patterns('',
    url(r'^$', index, name="index"),
    #url(r'^orig_index$', index, name="orig_index"),
    url(r'^about/$', about, name="about"),
    url(r'^contact/$', contact, name="contact"),
    url(r'^coding/$', coding),
    url(r'^sitemap.txt/$', sitemap),
    url(r'^robots.txt/$', robots),
)

app/ydata/urls.py
# coding: utf-8

from django.conf.urls.defaults import *

urlpatterns = patterns('ydata.views',
    url(r'^uploadsf/(?P<id>\d+)/$', 'upload_single_file', name='uploadsf'),
    url(r'^attachment/(?P<id>\d+)/$', 'show_attachment', name='show_attachment'),
    url(r'^attachment/(?P<id>\d+)/remove/$', 'remove_attachment', name='delete_attachment'),
    url(r'^attachment/(?P<id>\d+)/download/$', 'download_attachment', name='download_attachment'),
)

urls.py
# coding: utf-8

try:
    import settings
except ImportError:
    import sys
    sys.stderr.write("import settting error!")
    sys.exit(1)


from django.conf.urls.defaults import *
from django_xmlrpc.views import handle_xmlrpc

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^ylinux/', include('ylinux.foo.urls')),
    # 注意 '' 和 ^$ 不同！
    # namespace 参考
    # http://docs.djangoproject.com/en/dev/topics/http/urls/#topics-http-defining-url-namespaces
    (r'', include('ylinux.app.home.urls', namespace='home')),
    (r'^admin/', include('ylinux.app.admin.urls', namespace='admin')),
    (r'^account/', include('ylinux.app.account.urls', namespace='account')),
    (r'^wiki/', include('ylinux.app.wiki.urls', namespace='wiki')), 
    (r'^blog/', include('ylinux.app.blog.urls', namespace='blog')),
    (r'^bbs/', include('ylinux.app.bbs.urls', namespace='bbs')),
    (r'^ydata/', include('ylinux.app.ydata.urls', namespace='ydata')),
    (r'^lab/', include('ylinux.app.ylab.urls', namespace='lab')),
    (r'^me/', include('ylinux.app.me.urls', namespace='me')),

    # 静态地址
    (r'^favicon\.ico$', 'django.views.generic.simple.redirect_to', {'url': settings.MEDIA_URL+'images/favicon.ico'}),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    #(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('django_xmlrpc.views',

    url(r'^xmlrpc/$', handle_xmlrpc, {}, name='xmlrpc'),
)

# 开发使用 django 自带的 web 服务器，需按照下面方法设置静态目录。如果放
# 到公网上，那么需要用你所有的 web 服务器设置静态目录。一般在共享主机的
# 环境里，针对 apache 可以用 .htaccess 实现

# 另外要注意的是，如果打开 admin 功能，就不要用 static 作为 url 前部分。

# 如果用 'show_indexes' 打开目录显示功能，可以在定义一个
# static/directory_index.html 模板。

if (settings.DEBUG):
    urlpatterns += patterns ('',
        (r'^ymedia/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    )

app/home/forms.py
# coding: utf-8

from django import forms

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField()
    sender = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)

app/home/views.py
# coding: utf-8

from forms import ContactForm
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect,HttpResponse
from django.template import RequestContext
from django.shortcuts import get_object_or_404
from django.core.urlresolvers import reverse

from account.models import User
from ydata.models import Catalog, Topic, Post
from ydata.util import render_to, build_form, get_parents


@render_to('home/index.html')
def index(request):

    topics = Topic.objects.all()[:10]
    posts = Post.objects.all().order_by('-updated')[:10]
    all_user = User.objects.all()
    if all_user:
        new_register_user = all_user.order_by('-date_joined')[0]
    else:
        new_register_user = None

    return {'title':'首页', 'topics':topics, 'posts':posts, 
            'new_register_user':new_register_user}


def about(request):
    return render_to_response('home/about.html',{'title':"关于",},
                              context_instance=RequestContext(request))

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            sender = form.cleaned_data['sender']

            recipients = ['ylinux.admin@gmail.com','lijian.gnu@gmail.com',]
            recipients.append(sender)

            from django.core.mail import send_mail
            send_mail (subject,message,sender,recipients)
            return render_to_response('home/thanks.html',{'title':"感谢",},
                                      context_instance=RequestContext(request))
            #return HttpResponseRedirect('/thanks/')
    else:
        form = ContactForm()

        return render_to_response('home/contact.html',
                                  {'title':"联系",'form':form,},
                                  context_instance=RequestContext(request))

#def thanks(request):
#    return render_to_response('home/thanks.html',{'title':"感谢",},
#                              context_instance=RequestContext(request))


def coding(request):
    return render_to_response('home/coding.html',{'title':"Coding 之中",},
                              context_instance=RequestContext(request))


def sitemap(request):
    from ydata.models import Topic
    topics = Topic.objects.all()
    urls = []
    for t in topics:
        url = reverse ('wiki:show_topic', args=[t.id])
        urls.append('http://ylinux.org'+url+'\n')
    return HttpResponse(urls)

def robots(request):
    return HttpResponse('User-agent: * ' + '\n' + 'Allow: /')

@render_to('home/index_foolday.html')
def index_foolday(request):
    return {}

templates/home/about.html
{% extends "home/base.html" %}

{% block content %}
<p>YLinux 正在开发中, 感谢您的关注，欢迎您的建议或批评！</p>
<p>目前社区使用 Django 开发，项目源码在 github 上，欢迎感兴趣的朋友一起参与进来！</p>
<p>Github 上的项目地址：<a href="http://github.com/jianlee/ylinux/tree/master" target="_blank">http://github.com/jianlee/ylinux/tree/master</a></p>
<pre>git clone git://github.com/jianlee/ylinux.git</pre>

<h2>我们的讨论组:</h2>
<table border=0 style="background-color: #fff; padding: 5px;" cellspacing=0>
  <tr><td> <img src="https://groups.google.com/intl/en/images/logos/groups_logo_sm.gif" height=30 width=140 alt="Google Groups"> </td></tr>
  <tr><td><b>参加 YLinux 讨论组</b></td></tr>
  <form action="https://groups.google.com/group/ylinux?hl=zh-CN/boxsubscribe"><tr><td> 您的 Email : <input type=text name=email> <input type=submit name="sub" value="订阅"></td></tr></form>
  <tr><td><a href="https://groups.google.com/group/ylinux?hl=zh-CN">先看看讨论组</a></td></tr>
</table>
<p>任何问题和建议都可以在这里讨论</p>

{% endblock %}

templates/home/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="zh" lang="zh">

  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="google-site-verification" content="2dFdZjchnNfxrEjgxT9Uj_oeqHOtAcEykLwQZ5HCbSY" />
    <link REL="SHORTCUT ICON" HREF="{{ MEDIA_URL }}images/favicon.ico">
    <link rel="stylesheet" href="{{ MEDIA_URL }}themes/{% if theme %}{{ theme }}{% else %}default{% endif %}/main.css" />
    <link rel="stylesheet" href="{{ MEDIA_URL }}themes/{% if theme %}{{ theme }}{% else %}default{% endif %}/home.css" />
    {% block title %}{% if title %}<title>{{ title }} - YLinux.org</title>{% else %}<title>YLinux.org</title>{% endif %}{% endblock %}
    <link rel="alternate" type="application/rss+xml" title="RSS 2.0" href="/wiki/topic/news/" />
    <script type="text/javascript" src="{{ MEDIA_URL }}js/jquery-1.6.2.min.js" ></script>
    <script type="text/javascript" src="{{ MEDIA_URL }}js/ylinux.js" ></script>
  </head>

  <!-- body 用 container 包容，分4块： header,navigator,content,footer -->  
  <body>
    <div id="container">

      <div id="header">

        <div id="logo"><a href="/"><img src="{{ MEDIA_URL }}images/ylinux-logo.gif" alt="YLinux"/></a></div>
        <div id="welcome"><span>我们不只关注 GNU/Linux ！</span></div>

        <div class="right">

          <div id="tools">
            <form method="get" action="http://www.google.com/search" target="google_window">
              <input type="text" name="as_q" size="16" maxlength="255" value="" id="s"/>
              <input type="image" src="/ymedia/images/btn_search_box.gif" width="27" height="24" id="go" alt="Search" title="Search" />
              <!--<input type="submit" name="sa" value="搜索"/>-->
              <input name="as_sitesearch" value="ylinux.org" type="hidden"/>
              <input name="newwindow" value="1" type="hidden"/>
              <input name="complete" value="1" type="hidden"/>
              <input name="forid" value="zh-CN" type="hidden"/>
              <input type="hidden" name="num" value="10"/>
              <input name="btnG" value="Google+%E6%90%9C%E7%B4%A2&" type="hidden"/>
              <input name="as_ft" value="1" type="hidden"/>
              <input name="as_qdr" value="all" type="hidden"/>
              <input name="as_occt" value="any" type="hidden"/>
              <input name="as_dt" value="i" type="hidden"/>
            </form>
          </div>

          <div id="account">
            {% if user.is_authenticated %}
            欢迎回来，<a href="{% url account:show_user user.id %}"><b>{{ user }}</a></b>
            {% if user.is_staff %} | <a href="{% url admin:index %}">管理界面</a> | {% endif %}
            <span id="logout"><button type="button" onclick="javascript: ajax_logout()">退出</button></span>
            {% else %}
            <!--<a href="{% url account:login %}">登录</a> <a href="{% url account:register %}"><b>注册</b></a>-->
            <span id="login"><button type="button" onclick="javascript: ajax_create_login()">登录</button></span>
            <span id="register"><button type="button">注册</button></span>
            {% endif %}
          </div>

        </div>

        <div id="navigator">
          <span>
            <a href="/" title="YLinux.org 的主页">首页</a>
            <a href="/coding" title="此部分还在开发中 ...">新闻</a>
            <a href="/me" title="此部分还在开发中 ...">ME</a>
            <a href="/coding" title="此部分还在开发中 ...">项目</a>
            <a href="/wiki" title="综合知识之库">知识库</a>
          </span>
          <a href="/wiki/topic/news/"><img src="{{ MEDIA_URL }}images/feed.gif" alt="订阅最近动态"/></a>
        </div>

      </div>
      <!-- 结束 header -->



      <!-- 开始 content -->
      <div id="content">
      {% block content %}{% endblock %}
      </div>
      <!-- 结束 content -->

      <!-- 开始 footer -->
      <div id="footer">
        版权 &copy <a href="http://ylinux.org">YLinux.org</a> |
        <a href="/about">关于</a> |
        <a href="/contact">联系</a> |
      </div>
      <!-- 结束 footer -->
      
    </div>
    <!-- 结束 container -->
    </body>
  </html>

templates/home/coding.html
{% extends "home/base.html" %}

{% block content %}

<h3>感谢您的关注</h3>

<p>正在开发中 ... ...</p>


<h3>期待您的参与</h3>

<p>目前社区使用 Django 开发，项目源码在 github 上，欢迎感兴趣的朋友一起参与进来！</p>
<p>Github 上的项目地址：<a href="http://github.com/jianlee/ylinux/tree/master" target="_blank">http://github.com/jianlee/ylinux/tree/master</a></p>
<pre>git clone git://github.com/jianlee/ylinux.git</pre>


<h5>我们的讨论组:</h5>
<p style="color:red">现在请使用 YLinux <a href="{% url wiki:index %}">知识库</a> 的功能。</p>
<p>也许这里能给你更多帮助:</p>
<ul>
  <li><a href="/wiki/topic/75/">如何参与 YLinux 开发</a></li>
</ul>
{% endblock %}

templates/home/contact.html
{% extends "home/base.html" %}

{% block content %}
<p>YLinux 正在努力开发中，欢迎参加！</p>

<!--<p>联系管理员：</p>-->
<fieldset>
<legend>联系我们</legend>
<form action="" method="post">
<p><label for="id_subject">主题：</label> <input id="id_subject" type="text" name="subject" maxlength="100" /></p>
<p><label for="id_message">内容：</label><textarea name="message" id="id_message" ></textarea></p>
<p><label for="id_sender">E-mail：</label> <input type="text" name="sender" id="id_sender" /></p>
<input type="submit" value="发送信息" align="right"/>
</form>
</fieldset>

{% endblock %}

templates/home/index.html
{% extends "home/base.html" %}

{% block content %}
<script type="text/javascript">

    $(document).ready( function () {

        // 显示更新信息
        $("#show-update").load("{% url wiki:ajax_show_update %}", function () {
            $(this).addClass("list-catalog-done");
        });

    });

</script>

<span class="welcome-newuser">{% if new_register_user %}欢迎新用户：<a href="{% url account:show_user new_register_user.id %}">{{ new_register_user }}</a>{% endif %}</span>
<div class="intro">

<p>
  YLinux 社区研究中文计算机科学，不只是 GNU/Linux 。中文计算机科学应该是这样：“<span class="ylinux-goal">任何以中文为母语的人，都能够使用中文和计算机进行交流</span>”。始学之，未存则建之。
</p>

</div>


<div id="show-update">
</div>
{% endblock %}

templates/home/index_foolday.html
<!DOCTYPE html>
<html>
<title>节日快乐！</title>
<body>
  <p>阿哦， 出错了！ 是不是？</p>
  <ul>
    <li>你敲回车键太给力了！它抗议!!</li>
    <li>你点击鼠标太大力了！它抗议！！</li>
    <li>你把屏幕弄破了，代码出来了！它抗议！！</li>
    <li>它们都在抗议！！！</li>
  </ul>
  <p>想看以前的YLinux吗？<br>给你出个主意：<br>起身，<br>原地倒立10妙钟，<br>回到电脑前，<br>向下滚动鼠标滚轮 ....</p>
  <p>哦，你还可以用<br>这个搜索找找以前的<br>YLinux到哪里去了： <br><a href="http://www.google.cn/intl/zh-CN/landing/teleport/" target="_blank">谷歌穿越搜索</a></p>
  <img src="http://ylinux.org/ydata/attachment/2/download/" alt="" style="position: absolute; left: 50%; top: 50%; margin-left: -285px; margin-top: -190px;">
  <p style="color:green; margin-top:1000px;">愚人节快乐！ 哦，还想 YLinux 吗？ 点这里看看： <a href="/orig_index">旧约</a></p>
</body>
</html>

templates/home/index_orig.html
{% extends "home/base.html" %}

{% block content %}

<p>感谢您的关注，社区正在开发中。欢迎您也能参与进来：<a href="/coding" onmouseover="this.style.color='green'" onMouseOut="this.style.color='#808284'">这里</a> 。{% if new_register_user %}欢迎新用户：<a href="{% url account:show_user new_register_user.id %}">{{ new_register_user }}</a>{% endif %}</p>

<div id="Stopic">
{% if topics %}
<h3>最近主题(top 10)：</h3>
  <ul>
  {% for t in topics %}
    <li>[{{ t.catalog }}] <a href="{% url wiki:show_topic t.id %}">{{ t.name }}</a></li>
  {% endfor %}
  </ul>
{% endif %}
</div>

<div id="Spost">
{% if posts %}
<h3>最近回复(top 10)：</h3>
  <ul>
  {% for p in posts %}
    <li>[{{ p.topic.catalog }}] <a href="{% url wiki:show_post p.id %}" title="{{ p }}">{{ p.topic }}</a> by <a href="{% url account:show_user p.user.id %}">{{ p.user }}</a></li>
  {% endfor %}
  </ul>
{% endif %}
</div>

{% endblock %}

templates/home/thanks.html
{% extends "home/base.html" %}

{% block content %}
<h2>感谢您的建议！</h2>

<p>您的消息已经发送到管理员邮箱 : <a href="mailto:ylinux.admin@gmail.com">ylinux.admin@gmail.com</a></p>
<p>所有接受者： {{ recipients }}</p>

<p>我们一定尽快做出响应！</p> 
{% endblock %}