app/wiki/urls.py
# coding: utf-8

from django.conf.urls.defaults import *
from wiki.views import LatestTopicFeed, LatestPostFeed

# patterns 的第一个元素是其他view的base路径
urlpatterns = patterns('wiki.views',

    url(r'^$', 'index', name='index'),

    # 一些不存在的对象
    url(r'^catalog_not_exist/(?P<id>\d+)/$', 'doesnotexist', {'type':'Catalog'}, name='catalog_not_exist'),
    url(r'^topic_not_exist/(?P<id>\d+)/$', 'doesnotexist', {'type':'Topic'}, name='topic_not_exist'),
    url(r'^post_not_exist/(?P<id>\d+)/$', 'doesnotexist', {'type':'Post'}, name='post_not_exist'),

    # Show Catalog : /前缀/catalog/<catalog-id>/
    # Show Topic : /前缀/topic/<topic-id>/
    # Show Post : /前缀/post/<post-id>/
    url(r'^catalog/$', 'catalog', name='catalogs'),
    url(r'^catalog/(?P<id>\d+)/$', 'catalog', name='show_catalog'),
    url(r'^catalog/(?P<id>\d+)/(?P<curpage>\d+)/$', 'catalog', name='show_catalog_with_page'),
    url(r'^topic/(?P<id>\d+)/$', 'topic', name='show_topic'),
    url(r'^post/(?P<id>\d+)/$', 'post', name='show_post'),

    # Add Topic :  /前缀/catalog/<catalog-id>/addtopic
    # Add Post  :  /前缀/topic/<topic-id>/addpost
    url(r'^topic/(?P<id>\d+)/addpost/$', 'add_post', name='add_post'),
    url(r'^catalog/(?P<id>\d+)/addtopic/$', 'add_topic', name='add_topic'),

    # Edit Topic :  /前缀/topic/<topic-id>/edit/
    url(r'^topic/(?P<id>\d+)/edit/$', 'edit_topic', name='edit_topic'),

    # Delete Topic : /前缀/topic/<topic-id>/delete/
    url(r'^topic/(?P<id>\d+)/delete/$', 'manage_topic', {'type':'delete'}, name='del_topic'),
    url(r'^topic/(?P<id>\d+)/recycled/$', 'manage_topic', {'type':'recycled'}, name='recycled_topic'),
    url(r'^topic/(?P<id>\d+)/hidden/$', 'manage_topic', {'type':'hidden'}, name='hidden_topic'),
    url(r'^topic/(?P<id>\d+)/disable_recycled/$', 'manage_topic', {'type':'disable_recycled'}, name='disable_recycled_topic'),
    url(r'^topic/(?P<id>\d+)/disable_hidden/$', 'manage_topic', {'type':'disable_hidden'}, name='disable_hidden_topic'),

    url(r'^post/(?P<id>\d+)/delete/$', 'del_post', name='del_post'),

    # Feeds
    url(r'^topic/news/$', LatestTopicFeed(), name='topic_news'),
    url(r'^post/news/$', LatestPostFeed(), name='post_news'),

    # AJAX Call
    url(r'^query_update/(?P<time>\d+)/ajax/$', 'ajax_query_update', name='ajax_query_update'),
    url(r'^show_update/ajax/$', 'ajax_show_update', name='ajax_show_update'),
    url(r'^catalog/(?P<id>\d+)/ajax/$', 'ajax_show_catalog', name='ajax_show_catalog'),
    url(r'^topic/(?P<topicID>\d+)/ajax_show_posts/$', 'ajax_show_posts', name='ajax_show_topic_posts'),
    url(r'^post/(?P<postID>\d+)/ajax_show_posts/$', 'ajax_show_posts', name='ajax_show_post_posts'),
    url(r'^catalog/(?P<id>\d+)/addtopic/ajax/$', 'ajax_add_topic', name='ajax_add_topic'), # by Plux <yfwz100@gmail.com>
    url(r'^topic/(?P<id>\d+)/ajax/$', 'ajax_topic', name='ajax_show_topic'), # by Plux <yfwz100@gmail.com>
    url(r'^post/(?P<postID>\d+)/editAJAX/$', 'editPostAJAX', name='editPostAJAX'),


    # 回复
    url(r'^topic/(?P<topicID>\d+)/replayAJAX/$', 'replayAJAX', name="replayTopicAJAX"),
    url(r'^post/(?P<postID>\d+)/replayAJAX/$', 'replayAJAX', name="replayPostAJAX"),
)

app/ydata/urls.py
# coding: utf-8

from django.conf.urls.defaults import *

urlpatterns = patterns('ydata.views',
    url(r'^uploadsf/(?P<id>\d+)/$', 'upload_single_file', name='uploadsf'),
    url(r'^attachment/(?P<id>\d+)/$', 'show_attachment', name='show_attachment'),
    url(r'^attachment/(?P<id>\d+)/remove/$', 'remove_attachment', name='delete_attachment'),
    url(r'^attachment/(?P<id>\d+)/download/$', 'download_attachment', name='download_attachment'),
)

urls.py
# coding: utf-8

try:
    import settings
except ImportError:
    import sys
    sys.stderr.write("import settting error!")
    sys.exit(1)


from django.conf.urls.defaults import *
from django_xmlrpc.views import handle_xmlrpc

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^ylinux/', include('ylinux.foo.urls')),
    # 注意 '' 和 ^$ 不同！
    # namespace 参考
    # http://docs.djangoproject.com/en/dev/topics/http/urls/#topics-http-defining-url-namespaces
    (r'', include('ylinux.app.home.urls', namespace='home')),
    (r'^admin/', include('ylinux.app.admin.urls', namespace='admin')),
    (r'^account/', include('ylinux.app.account.urls', namespace='account')),
    (r'^wiki/', include('ylinux.app.wiki.urls', namespace='wiki')), 
    (r'^blog/', include('ylinux.app.blog.urls', namespace='blog')),
    (r'^bbs/', include('ylinux.app.bbs.urls', namespace='bbs')),
    (r'^ydata/', include('ylinux.app.ydata.urls', namespace='ydata')),
    (r'^lab/', include('ylinux.app.ylab.urls', namespace='lab')),
    (r'^me/', include('ylinux.app.me.urls', namespace='me')),

    # 静态地址
    (r'^favicon\.ico$', 'django.views.generic.simple.redirect_to', {'url': settings.MEDIA_URL+'images/favicon.ico'}),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    #(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('django_xmlrpc.views',

    url(r'^xmlrpc/$', handle_xmlrpc, {}, name='xmlrpc'),
)

# 开发使用 django 自带的 web 服务器，需按照下面方法设置静态目录。如果放
# 到公网上，那么需要用你所有的 web 服务器设置静态目录。一般在共享主机的
# 环境里，针对 apache 可以用 .htaccess 实现

# 另外要注意的是，如果打开 admin 功能，就不要用 static 作为 url 前部分。

# 如果用 'show_indexes' 打开目录显示功能，可以在定义一个
# static/directory_index.html 模板。

if (settings.DEBUG):
    urlpatterns += patterns ('',
        (r'^ymedia/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    )

app/ydata/forms.py
# coding: utf-8
import os, datetime

from django.conf import settings
from django import forms

from ydata.models import Topic, Post, Reputation, Report, Attachment, TZ_CHOICES, PRIVACY_CHOICES
from ydata import settings as ydata_settings
 

class AddPostForm(forms.ModelForm):
    name = forms.CharField(label='标题', max_length=256,
           widget=forms.TextInput)
    attachment = forms.FileField(label='附件', 
                                 required=False)

    class Meta:
        model = Post
        fields = ['body']

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        self.topic = kwargs.pop('topic', None)
        self.ip = kwargs.pop('ip', None)
        super(AddPostForm, self).__init__(*args, **kwargs)

        if self.topic:
            self.fields['name'].widget = forms.HiddenInput()
            self.fields['name'].required = False

        self.fields['body'].widget = forms.Textarea(attrs={'class':'bbcode', 'rows':'10', 'cols':'60'})

        if not ydata_settings.ATTACHMENT_SUPPORT:
            self.fields['attachment'].widget = forms.HiddenInput()
            self.fields['attachment'].required = False

    def clean_attachment(self):
        if self.cleaned_data['attachment']:
            memfile = self.cleaned_data['attachment']
            if memfile.size > ydata_settings.ATTACHMENT_SIZE_LIMIT:
                raise forms.ValidationError('Attachment is too big')
            return self.cleaned_data['attachment']


    def save(self):
        post = Post(topic=self.topic, user=self.user, user_ip=self.ip, markup='none', body=self.cleaned_data['body'])
        self.topic.post_count += 1
        self.topic.save()
        self.topic.catalog.post_count += 1
        self.topic.catalog.save()
        post.updated = datetime.datetime.now();
        post.save()
        if ydata_settings.ATTACHMENT_SUPPORT:
            self.save_attachment(post, self.cleaned_data['attachment'])
        return post

    def save_attachment(self, post, memfile):
        if memfile:
            obj = Attachment(size=memfile.size, content_type=memfile.content_type,
                             name=memfile.name, post=post)
            dir = os.path.join(settings.MEDIA_ROOT, ydata_settings.ATTACHMENT_UPLOAD_TO)
            fname = '%d.0' % post.id
            path = os.path.join(dir, fname)
            file(path, 'w').write(memfile.read())
            obj.path = fname
            obj.save()


class AddTopicForm(forms.ModelForm):

    text = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Topic
        fields = ['catalog','name','markup']

    def __init__(self, *args, **kwargs):
        self.catalog = kwargs.pop('catalog', None)
        self.user = kwargs.pop('user', None)
        self.user_ip = kwargs.pop('user_ip', None)
        super(AddTopicForm, self).__init__(*args, **kwargs)

        self.fields['catalog'].initial = self.catalog.id
        if self.catalog:
            self.fields['catalog'].widget = forms.HiddenInput()

    def save(self):
        topic = Topic(name=self.cleaned_data['name'],
                user_ip=self.user_ip,
                markup=self.cleaned_data['markup'])
        topic.catalog=self.catalog
        topic.user=self.user
        topic.updated = datetime.datetime.now()
        topic.save()
        self.catalog.topic_count += 1
        self.catalog.save()
        text = self.cleaned_data['text'].encode('utf8')
        topic.save_file(text)
        return topic

class EditTopicForm(forms.ModelForm):

    text = forms.CharField(widget=forms.Textarea(
        attrs={'class':'markdown', 'rows':'20', 'cols':'65'}))


    class Meta:
        model = Topic
        fields = ['catalog','name','markup']

    def __init__(self, *args, **kwargs):
        self.old_text = kwargs.pop('text', None)
        self.user_ip = kwargs.pop('user_ip', None)
        super(EditTopicForm, self).__init__(*args, **kwargs)
        
        self.fields['text'].initial = self.old_text

    def save(self):
        topic = super(EditTopicForm, self).save(commit=False)
        topic.name = self.cleaned_data['name']
        topic.user_ip = self.user_ip
        topic.markup = self.cleaned_data['markup']
        topic.catalog=self.cleaned_data['catalog']
        topic.updated = datetime.datetime.now()
        topic.save()
        text = self.cleaned_data['text'].encode('utf8')
        topic.save_file(text)
        return topic

templates/wiki/DoesNotExist.html
{% extends 'wiki/base.html' %}
{% block content %}

<p>id 为 "{{ id }}" 的 "{{ type }}" 不存在！</p>

<p>返回 <a href="{% url wiki:index %}">知识库</a></p>

{% endblock %}

templates/wiki/add_post.html
{% extends 'wiki/base.html' %}
{% block extend_header %}
<link rel="stylesheet" href="{{ MEDIA_URL }}themes/default/main.css" />
<link rel="stylesheet" href="{{ MEDIA_URL }}themes/default/common.css" />
<!-- link rel="stylesheet" href="{{ MEDIA_URL }}themes/default/wiki_index.css" / -->
<link rel="stylesheet" href="{{ MEDIA_URL }}themes/default/topic.css" />
{% endblock %}

{% block content %}
<div id="addpost" class="box">
<div class="title">回复： {{ topic }}</div>

<form action="" method="post">
  {{ form.as_p }}
  <div class="submit">
    <p><input type="submit" value="发表回复" /><a href="javascript:history.go(-1)">返回</a></p>
  </div>
</form>
</div>

<div id="posts" class="box">
{% if posts %}
    <h3 class="title">其他回复：</h3>
    {% for p in posts %}
    <p><a href="{% url account:show_user p.user.id %}">{{ p.user }}</a> 在 {{ p.updated }} 于 <a href="http://www.ip138.com/ips.asp?ip={{ p.user_ip }}&action=2">{{ p.user_ip }}</a></p>
    <p>{{ p.body }}</p>
    {% endfor %}
{% else %}
    <p>目前还没有任何回复</p>
{% endif %}
</div>

{% endblock %}

templates/wiki/add_topic.html
{% extends 'wiki/base.html' %}

{% block extend_header %}
<link rel="stylesheet" href="{{ MEDIA_URL }}themes/default/main.css" />
<link rel="stylesheet" href="{{ MEDIA_URL }}themes/default/common.css" />
<link rel="stylesheet" href="{{ MEDIA_URL }}themes/default/wiki_index.css" />

<script type="text/javascript" src="/ymedia/js/upload.js"></script>
{% endblock %}

{% block content %}

{% if form.errors %}
<div id="form-error">
  <p>提交表格有错误发生：</p>
  <ul>
    {% for field in form %}
    {% if field.errors %}
    <li>{{ field.name }}： {{ field.errors|striptags }}</li>
    {% endif %}
    {% endfor %}
  </ul>
</div>
{% endif %}

<div class="box">
<div class="title">新建主题</div>
<div class="content">
<form action="" method="POST">
    {{ form.as_p }}
  　 <p><input type="submit" value="发表"></p>

</form>

<div id="uploadList">
  <p>附件管理</p>
  <table>
    <tbody id="upload">
      <tr>
        <th>ID</th>
        <th>名字</th>
        <th>描述</th>
      </tr>
    </tbody>
  </table>
</div>

<div id="uF">
  <table>
    <tr>
      <td id="upload_form"></td>
    </tr>
    <tr>
      <td><button onclick="CreateUploadForm();">添加附件</button></td>
    </tr>
  </table>
</div>

</div> {# class:content #}
</div> {# class:box #}


{% endblock %}

templates/wiki/ajax_add_topic.html
<div id="wiki-container-main-title">
  <span>
    <a href="javascript: void(0)" onclick="ajax_list_catalog('{% url wiki:ajax_show_update %}')">开始</a>
    {% for pid,name in parents %}
      &gt; <a href="javascript: void(0)" onclick="ajax_list_catalog('{% url wiki:ajax_show_catalog pid %}')">{{ name }}</a>
    {% endfor %}

    {% if user.is_authenticated %}
    <!-- <span class="right"><a href="{% url wiki:index %}" target="_self" id="write_new">返回</a></span> -->
    {% endif %}

  </span>
</div>
<!--
<p>
  <a href="{% url wiki:index %}">知识库</a>
  {% for id,name in parents %}
  | <a href="{% url wiki:show_catalog id %}">{{ name }}</a>
  {% endfor %}
  | 发表新主题
</p>
-->


{% if form.errors %}
<div id="form-error">
  <p>提交表格有错误发生：</p>
  <ul>
    {% for field in form %}
    {% if field.errors %}
    <li>{{ field.name }}： {{ field.errors|striptags }}</li>
    {% endif %}
    {% endfor %}
  </ul>
</div>
{% endif %}

<form action="{% url wiki:add_topic id%}" method="POST">
<!--  
  <p><label for="id_name">标题:</label> <input id="id_name" type="text" name="name" maxlength="256" /></p>
  <p>
    <label for="id_markup">语法:</label>
    <select name="markup" id="id_markup">
      <option value="bbcode">bbcode</option>
      <option value="markdown" selected="selected">markdown</option>
    </select>
    <span><a href="/wiki/topic/8/" target="_blank">Markdown 标记语言使用帮助</a></span>
  </p>
  <p>
    <label for="id_text">正文:</label>
    <textarea id="id_text" rows="20" cols="60" name="text"></textarea>
    <input type="hidden" name="catalog" value="4" id="id_catalog" />
  </p>
  　 <p><input type="submit" value="发表"></p>
-->
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="发表" />
</form>

<!--
<div id="uploadList">
  <p>附件管理</p>
  <table>
    <tbody id="upload">
      <tr>
        <th>ID</th>
        <th>名字</th>
        <th>描述</th>
      </tr>
    </tbody>
  </table>
</div>
<div id="uF">
  <table>
    <tr>
      <td id="upload_form"></td>
    </tr>
    <tr>
      <td><button onclick="CreateUploadForm();">添加附件</button></td>
    </tr>
  </table>
</div>
-->

templates/wiki/ajax_show_catalog.html
{% if error %}
{{ error }}
{% else %}
<script type="text/javascript">

    $(document).ready( function () {
       $('tbody tr:odd').addClass("tr-odd");
       $('#write_new').click(function(event) {
	  event.preventDefault();
	  ajax_list_catalog($(this).attr('href') + 'ajax');
       });
    });
</script>

<div id="wiki-container-main-title">
  <span>
    <a href="javascript: void(0)" onclick="ajax_list_catalog('{% url wiki:ajax_show_update %}')">开始</a>
    {% for id,name in parents %}
    &gt; <a href="javascript: void(0)" onclick="ajax_list_catalog('{% url wiki:ajax_show_catalog id %}')">{{ name }}</a>
    {% endfor %}

    {% if user.is_authenticated %}
    <span class="right"><a href="{% url wiki:add_topic catalog.id %}" target="_blank" id="write_new">写文章</a></span>
    {% endif %}

  </span>
</div>



{% if catalog.children %}
<table colspan="2">
  <caption>子论坛信息</caption>

  <thead>
    <tr>
      <th>版面</th>
      <th>主题数</th>
      <th>最新主题</th>
    </tr>
  </thead>

  <tbody>
    {% for c in catalog.children %}
    <tr>
      <td><a href="javascript: void(0)" onclick="ajax_list_catalog('{% url wiki:ajax_show_catalog c.id %}')">{{ c.name }}</a></td>
      <td>{{ c.topic_count }}</td>
      <td>
        <span class="newest-topic">
          {% if c.last_topic %}
          <a href="{% url wiki:show_topic c.last_topic.id %}" target="_blank">{{ c.last_topic }}</a> by 
          <a href="{% url account:show_user c.last_topic.user.id %}" target="_blank">{{c.last_topic.user}}</a>
          {% else %}
          无新帖
          {% endif %}
        </span>
      </td>
    </tr>
    {% endfor %}
  </tbody>

</table>
{% endif %}


{% if topics %}
<table>
  <caption>主题列表</caption>

  <thead>
    <tr>
      <th>主题</th>
      <th>最新回复</th>
      <th>回复</th>
      <th>查看</th>
    </tr>
  </thead>

  <tbody>
    {% for t in topics %}
    <tr>
      <td><a href="{% url wiki:show_topic t.id %}" target="_blank">{{ t.name }}</a></td>
      <td>
        <span class="newest-post">
          {% if t.last_post %}
          <span><a href="/wiki/topic/{{ t.id }}#post{{ t.last_post.id }}" target="_blank">{{ t.last_post }}</a></span><br/>
          By
          <a href="{% url account:show_user t.last_post.user.id %}" target="_blank">{{t.last_post.user}}</a>
          <span class="time">{{ t.updated|date:"Y年m月d日 H:i" }}</span>
          {% else %}
          无回复
          {% endif %}
        </span>
      </td>
      <td>{{ t.post_count }}</td>
      <td>{{ t.view_count }}</td>
    </tr>
    {% endfor %}
  </tbody>

</table>
{% endif %}



{% endif %}

templates/wiki/ajax_show_update.html
<div id="update-container" class="clearfix">

  <div id="newest-topic-container">
    {% if topics %}
    <div class="newest-container-title">
      <h3>最新文章：</h3>
    </div>
    {% for t in topics %}
    <div class="newtopic">
      <div class="newtopic-title">
        <span><a href="{% url wiki:show_topic t.id %}" target="_blank">{{ t.name }}</a></span>
      </div>
      <div class="newtopic-info">
        <span class="user"><a href="{% url account:show_user t.user.id %}" target="_blank">{{ t.user }}</a></span>
        <span class="time">{{ t.updated|date:"Y年m月d日 H:i" }}</span>
      </div>
    </div>
    {% endfor %}
    {% else %}
    <p>无新文章</p>
    {% endif %}
  </div>


  <div id="newest-post-container">
    {% if posts %}
    <div class="newest-container-title">
      <h3>最新回复：</h3>
    </div>
    {% for p in posts %}
    <div class="newpost">
      <div class="newpost-title">
        <a href="/wiki/topic/{{ p.topic.id }}#post{{ p.id }}" target="_blank">{{ p }}</a>
      </div>
      <div class="newpost-info">
        <span class="user"><a href="{% url account:show_user p.user.id %}" target="_blank">{{ p.user }}</a></span>
        <span class="time">{{ p.updated|date:"Y年m月d日 H:i" }}</span>
      </div>
    </div>
    {% endfor %}
    {% endif %}
  </div>

</div>

templates/wiki/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
          "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="zh" lang="zh">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link REL="SHORTCUT ICON" HREF="{{ MEDIA_URL }}images/favicon.ico">
    <title>{{ title }}{% if title %} - {% endif %}YLinux.org</title>
    <script type="text/javascript" src="{{ MEDIA_URL }}js/jquery-1.6.2.min.js" ></script>
    {% block extend_header %}
    {% endblock %}
    <script type="text/javascript">
      $(document).ready(function () {
        $(".tools .s").focus(function() {
          $(this).attr('value', "");
          $(this).css("color", "#000");
        }).blur(function() {
          $(this).attr('value', "搜索");
          $(this).css("color", "#ccc");
        });
      });
    </script>
  </head>

  <!-- body 用 container 包容，分4块： header,navigator,content,footer -->  
  <body id="RoundAngle">

    <div id="container">
      <!-- 开始 header (分2块: logo,account) -->
      <div id="header">
        <div id="logo"><a href="/"><img src="{{ MEDIA_URL }}images/ylinux-logo.gif" alt="YLinux"/></a></div>
        <div id="welcome"><span>我们不只关注 GNU/Linux ！</span></div>

        <div id="navigator">
        <a href="/wiki/topic/news/"><img src="{{ MEDIA_URL }}images/feed.gif" alt="订阅最近动态"/></a>
        <span>
            <a href="/">首页</a>
            <a href="/coding">新闻</a>
            <a href="/blog">博客</a>
            <a href="/coding">项目</a>
            <a href="/wiki">知识库</a>
        </span>
        </div>
        <div id="account">
        {% if user.is_authenticated %}
        欢迎回来，<a href="{% url account:show_user user.id %}"><b>{{ user }}</a></b>
        {% if user.is_staff %} | <a href="{% url admin:index %}">管理界面</a> | {% endif %}
        <span id="logout"><button type="button" onclick="javascript: ajax_logout()">退出</button></span>
        {% else %}
        <!--<a href="{% url account:login %}">登录</a> <a href="{% url account:register %}"><b>注册</b></a>-->
        <span id="login"><button type="button" onclick="javascript: ajax_create_login()">登录</button></span>
        <span id="register"><button type="button">注册</button></span>
        {% endif %}
        </div>
        {% block header %}
        <div class="clear-fix"></div>
        {% endblock %}
      </div>
      <!-- 结束 header -->
      <!-- 开始 main -->
      <div id="main">
        {% block content %}
        <!-- main content here. -->
        {% endblock %}
        <div class="clear-fix"></div>
        <div class="manage">
            <div class="tools">
                <div class="message left" style="float:left">
                找不到合适的结果？尝试：
                </div>
            {% if user.is_authenticated and catalog %}
                <a class="new-knowlg-btn" href="{% url wiki:add_topic catalog.id %}">新建知识点</a>
            {% endif %}
                <form method="get" action="http://www.google.com/search" target="google_window">
                    <input type="text" name="as_q" size="16" maxlength="255" value="搜索" class="s"/>
                    <input type="image" src="/ymedia/images/btn_search_box.gif" width="27" height="24" class="go" alt="Search" title="Search" />
                    <input name="as_sitesearch" value="ylinux.org" type="hidden"/>
                    <input name="newwindow" value="1" type="hidden"/>
                    <input name="complete" value="1" type="hidden"/>
                    <input name="forid" value="zh-CN" type="hidden"/>
                    <input type="hidden" name="num" value="10"/>
                    <input name="btnG" value="Google+%E6%90%9C%E7%B4%A2&" type="hidden"/>
                    <input name="as_ft" value="1" type="hidden"/>
                    <input name="as_qdr" value="all" type="hidden"/>
                    <input name="as_occt" value="any" type="hidden"/>
                    <input name="as_dt" value="i" type="hidden"/>
                </form>
            </div>
        </div>
        <div class="clear-fix"></div>
      </div>
      <!-- 结束 main -->

      <!-- 开始 footer -->
      <div id="footer">
        版权 &copy; <a href="http://ylinux.org">YLinux.org</a> |
        <a href="/about">关于</a> |
        <a href="/contact">联系</a> |
        <!--
        <script language="javascript" type="text/javascript" src="http://js.users.51.la/3151082.js"></script>
        <noscript><a href="http://www.51.la/?3151082" target="_blank"><img alt="51统计" src="http://ylinux.org/ylinux/media/default/ylinux/images/51.gif"/></a></noscript>
        -->
      </div>
      <!-- 结束 footer -->
      
    </div>
    <!-- 结束 container -->

  </body>
</html>

templates/wiki/edit.html
{% extends 'wiki/base.html' %}

{% block content %}
<div id="edit-topic" class="box">
	<h1 class="title">Edit</h1>

	<form action="" method="post">

		<div class="field_wrapper required{% if form.name.errors %} errors{% endif %}" id="field_name">
			<label for="id_name" class="field_name"><strong>Page name</strong></label>
			{% if form.name.errors %}{{ form.name.errors }}{% endif %}
			<div class="field text_input">
				{{ form.name }}
			</div>
		</div>

		<div class="field_wrapper required{% if form.content.errors %} errors{% endif %}" id="field_content">
			<label for="id_content" class="field_name"><strong>Content</strong></label>
			{% if form.content.errors %}{{ form.content.errors }}{% endif %}
			<div class="field textarea">
				{{ form.content }}
			</div>
		</div>

		<div class="submit">
			<input type="submit" value="Save" />
		</div>

	</form>
</div>
{% endblock %}